/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WritingSlugRouteImport } from './routes/writing.$slug'
import { Route as ApiPublicSpotifyCallbackRouteImport } from './routes/api/public/spotify/callback'
import { Route as ApiPublicSpotifyConnectRouteImport } from './routes/api/public/spotify/connect'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSpotifyCallbackRoute =
  ApiPublicSpotifyCallbackRouteImport.update({
    id: '/api/public/spotify/callback',
    path: '/api/public/spotify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSpotifyConnectRoute = ApiPublicSpotifyConnectRouteImport.update({
  id: '/api/public/spotify/connect',
  path: '/api/public/spotify/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/api/public/spotify/callback': typeof ApiPublicSpotifyCallbackRoute
  '/api/public/spotify/connect': typeof ApiPublicSpotifyConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/api/public/spotify/callback': typeof ApiPublicSpotifyCallbackRoute
  '/api/public/spotify/connect': typeof ApiPublicSpotifyConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/api/public/spotify/callback': typeof ApiPublicSpotifyCallbackRoute
  '/api/public/spotify/connect': typeof ApiPublicSpotifyConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/writing/$slug'
    | '/api/public/spotify/callback'
    | '/api/public/spotify/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/writing/$slug'
    | '/api/public/spotify/callback'
    | '/api/public/spotify/connect'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/writing/$slug'
    | '/api/public/spotify/callback'
    | '/api/public/spotify/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WritingSlugRoute: typeof WritingSlugRoute
  ApiPublicSpotifyCallbackRoute: typeof ApiPublicSpotifyCallbackRoute
  ApiPublicSpotifyConnectRoute: typeof ApiPublicSpotifyConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/spotify/callback': {
      id: '/api/public/spotify/callback'
      path: '/api/public/spotify/callback'
      fullPath: '/api/public/spotify/callback'
      preLoaderRoute: typeof ApiPublicSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/spotify/connect': {
      id: '/api/public/spotify/connect'
      path: '/api/public/spotify/connect'
      fullPath: '/api/public/spotify/connect'
      preLoaderRoute: typeof ApiPublicSpotifyConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WritingSlugRoute: WritingSlugRoute,
  ApiPublicSpotifyCallbackRoute: ApiPublicSpotifyCallbackRoute,
  ApiPublicSpotifyConnectRoute: ApiPublicSpotifyConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
